name: Build and Test

on: [push]
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_BUILD_FOLDER: build
  SOLUTION_FILE_PATH: ./build/NeatReflection.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
      with:
        build-dir: ${{env.SOLUTION_BUILD_FOLDER}}
        generator: Visual Studio 17 2022
          
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Run Tests
      working-directory: ${{env.GITHUB_WORKSPACE}}/${{env.SOLUTION_BUILD_FOLDER}}/tests/Debug
      run: NeatReflectionTestRunner.exe
